use_frameworks!

target 'UIBezierPath-Query_Example' do
  pod 'UIBezierPath-Query', :path => '../'
  pod 'PocketSVG', '2.0.0'

  target 'UIBezierPath-Query_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
